# Generated by Django 5.1.2 on 2024-10-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/default/project_default.jpg', upload_to='projects/project/'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='image',
            field=models.ImageField(default='projects/default/project_default.jpg', upload_to='projects/subtask/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='projects/default/project_default.jpg', upload_to='projects/task/'),
        ),
    ]
