# Generated by Django 5.1.2 on 2024-10-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecordsIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('income_type', models.CharField(choices=[('client_payment', 'Client Payment'), ('investment', 'Investment'), ('grant', 'Grant'), ('revenue', 'Revenue'), ('loan', 'Loan'), ('donation', 'Donation'), ('other', 'Other')], max_length=20)),
                ('price', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('received', 'received'), ('canceled', 'canceled')], max_length=11)),
                ('receive_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_incomes', to=settings.AUTH_USER_MODEL)),
                ('who_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecordsSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('paid', 'paid'), ('canceled', 'canceled')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('spent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spent_incomes', to=settings.AUTH_USER_MODEL)),
                ('who_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
