# Generated by Django 5.1.2 on 2024-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecordsincome',
            name='source',
        ),
        migrations.AddField(
            model_name='financialrecordsspent',
            name='spent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
