# Generated by Django 5.1.2 on 2024-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial', '0003_alter_financialrecordsincome_received_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecordsspent',
            name='spent_type',
            field=models.CharField(choices=[('salary', 'Salary'), ('equipment', 'Equipment'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('tax', 'Tax'), ('maintenance', 'Maintenance'), ('travel', 'Travel'), ('supplies', 'Supplies'), ('advertising', 'Advertising'), ('insurance', 'Insurance'), ('consultant_fee', 'Consultant Fee'), ('loan_repayment', 'Loan Repayment'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], default=0.0004940711462450593, max_length=20),
            preserve_default=False,
        ),
    ]
